from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class FailureCode(StrEnum):
    BLOCKED_OFFICIAL_ROUTE_NOT_RECONCILED = "BLOCKED_OFFICIAL_ROUTE_NOT_RECONCILED"
    BLOCKED_PLAN_OR_CHATGPT_TIER_NOT_WRITE_CAPABLE = "BLOCKED_PLAN_OR_CHATGPT_TIER_NOT_WRITE_CAPABLE"
    BLOCKED_SECURE_TUNNEL_NOT_AVAILABLE = "BLOCKED_SECURE_TUNNEL_NOT_AVAILABLE"
    BLOCKED_HOST_MODEL_NOT_ATTESTED = "BLOCKED_HOST_MODEL_NOT_ATTESTED"
    BLOCKED_DOMAIN_NOT_ALLOWED = "BLOCKED_DOMAIN_NOT_ALLOWED"
    BLOCKED_REDIRECT_SCOPE_ESCAPE = "BLOCKED_REDIRECT_SCOPE_ESCAPE"
    BLOCKED_UNSAFE_URL = "BLOCKED_UNSAFE_URL"
    BLOCKED_SSRF_TARGET = "BLOCKED_SSRF_TARGET"
    BLOCKED_PROMPT_INJECTION_SUSPECTED = "BLOCKED_PROMPT_INJECTION_SUSPECTED"
    BLOCKED_PENDING_FINITE_WRITE_PERMIT_OR_EXPLICIT_SESSION_AUTHORIZATION = (
        "BLOCKED_PENDING_FINITE_WRITE_PERMIT_OR_EXPLICIT_SESSION_AUTHORIZATION"
    )
    BLOCKED_PENDING_HIGH_IMPACT_APPROVAL = "BLOCKED_PENDING_HIGH_IMPACT_APPROVAL"
    BLOCKED_PENDING_DUAL_CONTROL_APPROVAL = "BLOCKED_PENDING_DUAL_CONTROL_APPROVAL"
    BLOCKED_HIGH_RISK_ACTION_DISABLED = "BLOCKED_HIGH_RISK_ACTION_DISABLED"
    BLOCKED_PROHIBITED_ACTION = "BLOCKED_PROHIBITED_ACTION"
    BLOCKED_COST_UNKNOWN_OR_BUDGET_EXCEEDED = "BLOCKED_COST_UNKNOWN_OR_BUDGET_EXCEEDED"
    BLOCKED_AUTH_CHALLENGE_REQUIRES_USER = "BLOCKED_AUTH_CHALLENGE_REQUIRES_USER"
    BLOCKED_CAPTCHA_REQUIRES_USER = "BLOCKED_CAPTCHA_REQUIRES_USER"
    BLOCKED_STALE_PAGE_REVISION = "BLOCKED_STALE_PAGE_REVISION"
    BLOCKED_IDEMPOTENCY_CONFLICT = "BLOCKED_IDEMPOTENCY_CONFLICT"
    BLOCKED_PERMIT_INVALID = "BLOCKED_PERMIT_INVALID"
    BLOCKED_PERMIT_EXPIRED = "BLOCKED_PERMIT_EXPIRED"
    BLOCKED_PERMIT_SCOPE_MISMATCH = "BLOCKED_PERMIT_SCOPE_MISMATCH"
    BLOCKED_PERMIT_EXHAUSTED = "BLOCKED_PERMIT_EXHAUSTED"
    BLOCKED_APPROVAL_INVALID = "BLOCKED_APPROVAL_INVALID"
    BLOCKED_APPROVAL_EXPIRED = "BLOCKED_APPROVAL_EXPIRED"
    BLOCKED_APPROVAL_REPLAY = "BLOCKED_APPROVAL_REPLAY"
    BLOCKED_EVIDENCE_INCOMPLETE = "BLOCKED_EVIDENCE_INCOMPLETE"
    BLOCKED_POSTCONDITION_UNVERIFIED = "BLOCKED_POSTCONDITION_UNVERIFIED"
    BLOCKED_ROLLBACK_UNAVAILABLE_FOR_REQUIRED_REVERSIBILITY = (
        "BLOCKED_ROLLBACK_UNAVAILABLE_FOR_REQUIRED_REVERSIBILITY"
    )
    BLOCKED_SECRET_EXPOSURE_RISK = "BLOCKED_SECRET_EXPOSURE_RISK"
    BLOCKED_ILLEGAL_STATE_TRANSITION = "BLOCKED_ILLEGAL_STATE_TRANSITION"
    BLOCKED_CONCURRENT_REVISION_CONFLICT = "BLOCKED_CONCURRENT_REVISION_CONFLICT"
    BLOCKED_PRODUCTION_PROMOTION_NOT_APPROVED = "BLOCKED_PRODUCTION_PROMOTION_NOT_APPROVED"
    BLOCKED_SESSION_ALREADY_EXISTS = "BLOCKED_SESSION_ALREADY_EXISTS"
    BLOCKED_SESSION_NOT_FOUND = "BLOCKED_SESSION_NOT_FOUND"
    BLOCKED_SESSION_BINDING_MISMATCH = "BLOCKED_SESSION_BINDING_MISMATCH"
    BLOCKED_TRANSPORT_AUTHENTICATION_FAILED = "BLOCKED_TRANSPORT_AUTHENTICATION_FAILED"
    BLOCKED_TRANSPORT_ORIGIN_NOT_ALLOWED = "BLOCKED_TRANSPORT_ORIGIN_NOT_ALLOWED"
    BLOCKED_TRANSPORT_HOST_NOT_ALLOWED = "BLOCKED_TRANSPORT_HOST_NOT_ALLOWED"
    BLOCKED_TRANSPORT_PROTOCOL_VERSION = "BLOCKED_TRANSPORT_PROTOCOL_VERSION"
    BLOCKED_TRANSPORT_REQUEST_TOO_LARGE = "BLOCKED_TRANSPORT_REQUEST_TOO_LARGE"
    BLOCKED_TRANSPORT_BATCH_TOO_LARGE = "BLOCKED_TRANSPORT_BATCH_TOO_LARGE"
    BLOCKED_TRANSPORT_TOOL_NOT_ALLOWED = "BLOCKED_TRANSPORT_TOOL_NOT_ALLOWED"
    BLOCKED_TRANSPORT_RATE_LIMITED = "BLOCKED_TRANSPORT_RATE_LIMITED"
    BLOCKED_TRANSPORT_CAPACITY_EXHAUSTED = "BLOCKED_TRANSPORT_CAPACITY_EXHAUSTED"
    BLOCKED_JEV_DISABLED = "BLOCKED_JEV_DISABLED"
    BLOCKED_JEV_AUTHENTICATED_PAGE_DEFAULT_DENY = "BLOCKED_JEV_AUTHENTICATED_PAGE_DEFAULT_DENY"
    BLOCKED_JEV_SENSITIVE_PAGE_DEFAULT_DENY = "BLOCKED_JEV_SENSITIVE_PAGE_DEFAULT_DENY"
    BLOCKED_JEV_EXISTING_PERSONAL_PROFILE_DEFAULT_DENY = (
        "BLOCKED_JEV_EXISTING_PERSONAL_PROFILE_DEFAULT_DENY"
    )
    BLOCKED_JEV_UNSUPPORTED_FEATURE = "BLOCKED_JEV_UNSUPPORTED_FEATURE"
    BLOCKED_JEV_TARGET_NOT_EXACT_PUBLIC_HOST = "BLOCKED_JEV_TARGET_NOT_EXACT_PUBLIC_HOST"
    BLOCKED_JEV_EXTERNAL_MODEL_EGRESS_DEFAULT_DENY = (
        "BLOCKED_JEV_EXTERNAL_MODEL_EGRESS_DEFAULT_DENY"
    )
    BLOCKED_JEV_RUNTIME_AUTHORIZATION_REQUIRED = "BLOCKED_JEV_RUNTIME_AUTHORIZATION_REQUIRED"
    BLOCKED_JEV_EXECUTOR_UNAVAILABLE = "BLOCKED_JEV_EXECUTOR_UNAVAILABLE"
    BLOCKED_CUA_DISABLED = "BLOCKED_CUA_DISABLED"
    BLOCKED_CUA_DRIVER_BELOW_MINIMUM_VALIDATED_REFERENCE = (
        "BLOCKED_CUA_DRIVER_BELOW_MINIMUM_VALIDATED_REFERENCE"
    )
    BLOCKED_CUA_OPERATION_NOT_ALLOWLISTED = "BLOCKED_CUA_OPERATION_NOT_ALLOWLISTED"
    BLOCKED_CUA_BINDING_ARGUMENT_OVERRIDE = "BLOCKED_CUA_BINDING_ARGUMENT_OVERRIDE"
    BLOCKED_CUA_SESSION_BINDING_MISMATCH = "BLOCKED_CUA_SESSION_BINDING_MISMATCH"
    BLOCKED_CUA_EXISTING_PROFILE_DUAL_APPROVAL_REQUIRED = (
        "BLOCKED_CUA_EXISTING_PROFILE_DUAL_APPROVAL_REQUIRED"
    )
    BLOCKED_CUA_EXECUTOR_UNAVAILABLE = "BLOCKED_CUA_EXECUTOR_UNAVAILABLE"
    BLOCKED_SIDE_EFFECT_RECONCILIATION_REQUIRED = (
        "BLOCKED_SIDE_EFFECT_RECONCILIATION_REQUIRED"
    )
    FAILED_BROWSER_EXECUTION = "FAILED_BROWSER_EXECUTION"
    FAILED_ROLLBACK = "FAILED_ROLLBACK"
    FAILED_INTERNAL = "FAILED_INTERNAL"


@dataclass(slots=True)
class ControlPlaneError(RuntimeError):
    code: FailureCode
    message: str
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        RuntimeError.__init__(self, f"{self.code}: {self.message}")

    def to_dict(self) -> dict[str, Any]:
        return {
            "code": self.code.value,
            "message": self.message,
            "details": self.details,
        }
